#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if [ -f "$HOME/.config/yadm/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/yadm/Brewfile"
  fi

  set +e
  grep -qxF '/usr/local/bin/bash' /etc/shells
  retval=$?
  set -e
  if [ $retval -ne 0 ]; then
    echo "Adding Bash to allowed shells"
    echo "/usr/local/bin/bash" | sudo tee -a /etc/shells > /dev/null
  fi
  if [ "$SHELL" != "/usr/local/bin/bash" ]; then
    chsh -s /usr/local/bin/bash
  fi

fi

