#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if [ -f "$HOME/.config/yadm/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/yadm/Brewfile"
  fi

fi

