#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if [ -f "$HOME/.config/yadm/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/yadm/Brewfile"
  fi

  set +e
  grep -qxF '/usr/local/bin/bash' /etc/shells
  retval=$?
  set -e
  if [ $retval -ne 0 ]; then
    echo "Adding Bash to allowed shells"
    echo "/usr/local/bin/bash" | sudo tee -a /etc/shells > /dev/null
  fi
  if [ "$SHELL" != "/usr/local/bin/bash" ]; then
    chsh -s /usr/local/bin/bash
  fi

fi

if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
else
  echo "Updating ~/.vim/bundle/Vundle.vim..."
  pushd ~/.vim/bundle/Vundle.vim > /dev/null
  git pull
  popd > /dev/null
fi
vim -E -u NONE -S ~/.vimrc +PluginInstall +qall > /dev/null
